import { createHash } from 'node:crypto';

const fortunes: string[] = [
    'The neon signs flicker in your favor today — trust the signal.',
    'A stranger in the lower district carries the answer you seek.',
    'Your neural link hums with clarity. Act on instinct before midnight.',
    'The stars above the smog align — a rare fortune for the bold.',
    'Beware the corporation that offers gifts freely. Nothing in Neotropolis is free.',
    'An old frequency will reach you today. Listen carefully.',
    'The chrome moon rises in your sign — transformation is inevitable.',
    'You will find what you lost in the rain-slicked alley of memory.',
    'A datastream from the outer ring brings unexpected wealth.',
    'The circuits of fate have rerouted. Embrace the detour.',
    'Someone in the market district thinks of you when the lights go down.',
    'Your aura burns ultraviolet today — others will sense your power.',
    'The satellite gods smile upon your transactions. Trade boldly.',
    'A ghost in the machine whispers your true name. Acknowledge it.',
    'The rooftops call to you tonight. Ascend and find perspective.',
    'Rust and renewal share the same root. Let something old become new.',
    'Your reflection in the puddle knows more than you do. Study it.',
    'The next card you touch carries a message meant only for you.',
    'A synthetic dream will reveal a truth your waking mind ignores.',
    'The undercity hums a lullaby in your frequency. Rest well tonight.',
    'Mercury is in retrograde over Sector 7. Double-check all transmissions.',
    'A junction approaches — left leads to comfort, right leads to glory.',
    'The plasma aurora foretells a reunion with someone you once trusted.',
    'Your biorhythm syncs with the city grid today. You are unstoppable.',
    'An encrypted fortune hides inside a fortune. Look deeper.',
    'The vendor on the corner has something you need. Don\'t walk past.',
    'Tonight the holographic stars spell out your initials. Take the omen.',
    'A debt from a past life in the old city comes due. Pay it forward.',
    'Your shadow moves independently today — it knows where to go.',
    'The orbital station casts its blessing on water signs. Drink deep.',
    'Static on channel 9 carries a prophecy. Tune in at dusk.',
    'The scrapyard holds a relic that will change your trajectory.',
    'Trust the android with kind eyes. They remember the world before.',
    'A power surge in your district signals a shift in fortune.',
    'The constellation of the Soldering Iron rises — craft something today.',
    'Your lucky number pulses in the grid. Follow the repeating digits.',
    'Someone will ask you for directions. The answer you give changes both your paths.',
    'The vending machine on 5th and Neon owes you something. Collect.',
    'A solar flare disrupts the noise. In the silence, hear your purpose.',
    'The cyberdeck of destiny reshuffles. Your hand improves.',
    'Rain on chrome is today\'s blessing. Let it wash away doubt.',
    'The fortune teller in the plaza has been waiting for you specifically.',
    'A pirate signal carries your horoscope — chaotic but accurate.',
    'Your implants tingle at the threshold of a great discovery.',
    'The elevator to the upper levels opens for you today. Step in.',
    'A cat in the server room guards your secret. It is safe.',
    'The digital tarot draws The Tower reversed — disaster averted.',
    'Someone is writing your name in light on the side of a building.',
    'The monorail takes you somewhere you didn\'t intend. That\'s the point.',
    'Copper and silicon align in your favor. Build something lasting.',
    'The night market reveals its hidden stall to those who wander.',
    'An ancestor\'s code still runs in your blood. Honor it.',
    'The flickering streetlight is morse code from the universe. Decode it.',
    'A package arrives that you didn\'t order. Open it without fear.',
    'Venus transits the communications tower — love finds a new channel.',
    'The graffiti on the wall was painted for you. Read between the lines.',
    'Your energy signature peaks at golden hour. Schedule accordingly.',
    'A melody from a broken speaker carries your mantra today.',
    'The stars behind the billboards arrange in your birth pattern.',
    'An ally emerges from the crowd wearing your favorite color.',
    'The rust belt prophecy favors scavengers today. Search and prosper.',
    'Your neural pathways light up like the city skyline — brilliant.',
    'A forgotten password unlocks more than a door.',
    'The tides of the cooling reservoirs shift. Go with the current.',
    'Jupiter aligns with the broadcast tower — your voice carries far today.',
    'The drone overhead carries a blessing, not surveillance. Today.',
    'A circuit completes that was broken long ago. Feel the current.',
    'The hologram fortune teller winks — she sees your golden thread.',
    'Neon Pisces swim upstream through the data river. Follow them.',
    'Your reflection in a shop window wears a crown. Believe it.',
    'The junkyard oracle says: what others discard, you will treasure.',
    'A blackout in Sector 12 reveals the stars. Look up for once.',
    'The synthetic tea leaves arrange in the pattern of opportunity.',
    'Mars charges through the factory district — channel anger into creation.',
    'A child of the undercity carries wisdom older than the towers.',
    'Your access card resonates at a frequency of pure luck today.',
    'The abandoned subway echoes with the voice of your future self.',
    'Someone etched your sigil into the bridge railing. You are known.',
    'The algorithm of chance bends toward you. Play your hand.',
    'Tonight\'s acid rain washes clean the sins of yesterday\'s code.',
    'A mechanical bird lands on your windowsill. Accept the message.',
    'The satellite constellation forms your zodiac sign at 3:33 AM.',
    'Your thermal signature burns bright — you cannot hide, so shine.',
    'The recycled air today carries the scent of a memory worth revisiting.',
    'An old rival becomes an unlikely guide. Accept their olive branch.',
    'The power grid hums your birth frequency. The city knows you.',
    'A crack in the dome reveals true starlight. Bathe in it.',
    'The augmented reality overlay glitches to show you the truth.',
    'Neptune floods the lower bandwidth — dreams are prophetic tonight.',
    'Your credstick finds extra zeros today. Don\'t question it.',
    'A door you\'ve passed a thousand times finally stands open.',
    'The street preacher\'s sermon contains exactly one line meant for you.',
    'The constellation of the Wrench ascends — fix what has been broken.',
    'A stranger\'s tattoo mirrors your own story. Introduce yourself.',
    'The maglev arrives early today. So does your good fortune.',
    'Your horoscope was intercepted and upgraded by a benevolent hacker.',
    'The scaffolding on the old tower forms a sacred geometry. Study it.',
    'A message in a bottle floats down the drainage canal. Fish it out.',
    'Saturn\'s rings cast shadows on the solar array — patience is power.',
    'The black market astrologer says your chart is the rarest she\'s seen.',
    'Your DNA hums in harmony with the city\'s electromagnetic field.',
    'A stray signal from beyond the wall carries hope.',
    'The rooftop garden blooms out of season — miracles are near.',
    'The transit map, read sideways, spells out your destiny.',
    'An echo in the parking garage speaks your forgotten wish aloud.',
    'The moon over Neotropolis is artificial, but its pull on you is real.',
    'A courier drone drops a feather at your feet. You are chosen.',
    'Your bioelectric field disrupts cheap electronics today — you are charged.',
    'The constellation of the Cable Splice appears — connections strengthen.',
    'Someone hacked the billboard to show you your daily affirmation.',
    'The recycling plant turns your old regrets into raw material for joy.',
    'A phantom signal guides your steps. Don\'t resist.',
    'Uranus spins through the server farm — expect beautiful chaos.',
    'The fortune written on your coffee cup is no coincidence.',
    'A lens flare from the upper dome catches your eye. It\'s a sign.',
    'The underground river carries whispers of your coming success.',
    'Your chromatic aura shifts to gold at noon. That\'s when to act.',
    'The elevator knows which floor you truly need. Press no button.',
    'A synth-owl hoots your lucky number from the fire escape.',
    'The probability engines of Neotropolis recalculate in your favor.',
    'Your cybernetic stars are in alignment — the body electric sings.',
    'A forgotten shrine behind the dumpster answers one prayer per day.',
    'The static between stations carries the frequency of abundance.',
    'Today you walk the dragon line that runs beneath the boulevard.',
    'A mirror in the flea market shows you at your most powerful.',
    'The wind through the ventilation shafts carries pollen from the old world.',
    'Pluto transits the dead zone — rebirth emerges from abandonment.',
    'Your palm lines match the circuit diagram of a lucky machine.',
    'A sticker on a lamppost carries your personal glyph. Someone knows.',
    'The cosmic background radiation whispers: you are exactly where you should be.',
    'An anomaly in your sleep cycle tonight plants a seed of genius.',
    'The graffiti constellation above the overpass blesses night owls.',
    'Your electromagnetic signature attracts a beneficial stranger.',
    'A coin dropped in the gutter finds its way back to you tenfold.',
    'The smog parts briefly to reveal your ruling planet. Salute it.',
    'The rhythm of the jackhammers today matches your heartbeat — you are in sync.',
    'A ghost protocol activates in your favor. Old defenses now protect you.',
    'The binary stars of Neotropolis orbit closer tonight — duality resolves.',
    'An error in the matrix drops a rare item in your path.',
    'Your aura frequency jams surveillance. Move freely and fearlessly.',
    'The escalator to the skybridge hums a song your mother once sang.',
    'A solar panel tilts to follow you. Even the sun takes notice.',
    'The scrap metal in your pocket is worth more than you think.',
    'Tonight\'s dream holds coordinates. Write them down before they fade.',
    'The city grid reconfigures around your commute — paths clear.',
    'An old terminal in the library boots up just for you.',
    'The alignment of cooling towers channels fortune from the north.',
    'A street musician plays the melody of your unwritten future.',
    'Your retinal scan unlocks a door you didn\'t know existed.',
    'The vapor from the steam vent takes the shape of your answer.',
    'Mars and Mercury duel above the antenna array — speak, don\'t fight.',
    'A cache of pre-collapse wisdom surfaces in your feed today.',
    'The parking meter gives you extra time. So does the universe.',
    'Your shadow is slightly ahead of you — it knows the way.',
    'A projection malfunction shows you the city as it could be.',
    'The compass in your gut points true north today. Follow it.',
    'The constellations of rust on the water tower foretell prosperity.',
    'An undelivered letter finds you decades late. It\'s still relevant.',
    'The harmonic frequency of the subway matches your brainwaves — ride it.',
    'A firewall you didn\'t build protects you today. Thank it silently.',
    'The electric sheep in your dreams count you for a change.',
    'Your star chart overlaps with the city\'s power grid — synchronicity.',
    'A seed cracks through asphalt near your door. Growth is inevitable.',
    'The last vending machine on the block saves the best for you.',
    'Neptune\'s glow filters through the skylight — intuition sharpens.',
    'An old friend\'s voice echoes in the stairwell. They\'re thinking of you.',
    'The radio telescope picks up your frequency — the cosmos listens.',
    'A shortcut through the alley saves more than time today.',
    'Your lucky charm activates at sunset. Keep it close.',
    'The digital zodiac wheel spins — you land on the golden sector.',
    'A repaired wire somewhere in the district restores your signal.',
    'The tide of foot traffic parts around you. You are the stone.',
    'The constellation of the Motherboard rises — logic and intuition merge.',
    'A flickering ad contains a subliminal blessing. Absorb it.',
    'Your birth timestamp aligns with today\'s grid frequency — rare power.',
    'The rain tastes different today. The city is healing, and so are you.',
    'A lost drone returns carrying exactly what you need.',
    'The echo of your footsteps in the tunnel sounds like applause.',
    'The magnetic north of your heart points toward the right decision.',
    'An alley cat crosses your path — not bad luck, a guide.',
    'The broken clock in the plaza is right twice, and now is one of those times.',
    'Your reflection in the rain puddle smiles before you do.',
    'The frequency of the streetlight matches your alpha waves — think clearly.',
    'A crumpled note in your pocket that you didn\'t write holds advice.',
    'The orbital debris forms your initials tonight. Look up.',
    'The warmth of a heating vent carries a grandmother\'s blessing.',
    'The glitch in the crosswalk signal gives you an extra moment. Use it wisely.',
    'Someone upstream purified the water today. Drink and be renewed.',
    'The constellation of the Jumper Wire ascends — improvise boldly.',
    'A holographic rose blooms in a place only you can see.',
    'The city\'s heartbeat slows to match yours tonight. Rest.',
    'Your keycard opens a door that leads somewhere it shouldn\'t. Go.',
    'The astral bandwidth clears — your prayers upload at full speed.',
    'A voltage spike carries a message from your future self: keep going.',
    'The scrapheap zodiac says: Scorpio rules the recycling center today.',
    'Your peripheral vision catches a miracle. Turn your head slowly.',
    'The hydraulic hiss of the bus door whispers your name.',
    'A new mural on the overpass was painted in your colors.',
    'The telescope on the observation deck reveals your star — still burning.',
    'The last train carries more than passengers tonight. Board it.',
    'A misprint on your receipt spells out a word of encouragement.',
    'The feedback loop of the universe echoes your kindness back.',
    'Your electromagnetic field harmonizes with the checkout scanner — smooth transactions.',
    'The pigeon on the antenna is your spirit animal today. Observe it.',
    'A discarded book on the bench falls open to your page.',
    'The city\'s AI traffic system routes luck toward your coordinates.',
    'The chemical sunset paints your future in impossible colors.',
    'A stranger holds the elevator. In Neotropolis, that\'s a prophecy.',
    'The voltage in your veins runs higher today. Channel it.',
    'An old backup of your dreams finishes restoring tonight.',
    'The neon zodiac wheel on the casino spins in your direction.',
    'A signal bounces off three satellites and finds only you.',
    'The mushrooms growing in the server room are a sign of abundance.',
    'Your horoscope compiled and executed without errors today.',
    'The thermal vent creates a warm pocket just for you. Linger.',
    'A patch of real grass in the median whispers of better days coming.',
    'The randomness engine hiccups in your favor — take a chance.',
    'Your silhouette against the skyline matches a mythic figure. Own it.',
    'The broken escalator becomes stairs — and stairs still lead upward.',
    'A rogue pixel on the billboard winks at you. Wink back.',
    'The astral firewall thins tonight — download your destiny.',
    'Your commute today traces a sigil of protection on the city map.',
    'A child laughs in the corridor and the walls remember joy.',
    'The satellite that watches you also shields you from cosmic debris.',
    'An accidental harmony between car alarms sings your fortune.',
    'The LED constellation in the parking structure spells out: yes.',
    'Your body temperature matches the city\'s ambient reading — you are one.',
    'A rusted key in the gutter opens something you\'ve given up on.',
    'The probability cloud collapses in your favor today. Observe boldly.',
    'The graffiti artist who tagged your block left a ward of protection.',
    'An anomalous weather pattern brings exactly the sky you needed.',
    'The fiber optic cables beneath your feet glow with your potential.',
    'A backup generator kicks on just for your block. You are sustained.',
    'The digital fortune cookie cracks open: inside, your true name in hex.',
    'The stars don\'t care about the smog. Neither should your ambition.',
    'A benevolent worm crawls through the network, fixing things in your wake.',
    'The pendulum of the crane on the skyline swings toward yes.',
    'Your barcode, if scanned today, reads: priceless.',
    'The exhaust from the rooftop vent forms a halo above your building.',
    'A typo in the matrix spawns a door where there was a wall.',
    'The alignment of the dish antennas amplifies your intention tonight.',
    'Your footprints in the dust of the abandoned floor spell out: worthy.',
    'The city breathes in sync with you today. Exhale and let go.',
];

export function getFortune(uid: string): string {
    const date = new Date();
    const dateStr = `${date.getFullYear()}-${date.getMonth() + 1}-${date.getDate()}`;
    const hash = createHash('sha256').update(`${uid}:${dateStr}`).digest();
    return fortunes[hash[0]];
}
